# GitHub Labels Configuration
# This file defines the labels used in the repository

labels:
  # Priority labels
  - name: "priority: critical"
    color: "d73a4a"
    description: "Critical issues that need immediate attention"
  - name: "priority: high"
    color: "ff9800"
    description: "High priority issues"
  - name: "priority: medium"
    color: "ffc107"
    description: "Medium priority issues"
  - name: "priority: low"
    color: "4caf50"
    description: "Low priority issues"

  # Type labels
  - name: "type: bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "type: enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "type: documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "type: performance"
    color: "7057ff"
    description: "Performance improvements"
  - name: "type: security"
    color: "ff6b6b"
    description: "Security-related issues"

  # Status labels
  - name: "status: needs triage"
    color: "f9d0c4"
    description: "Needs to be triaged"
  - name: "status: in progress"
    color: "0075ca"
    description: "Work in progress"
  - name: "status: blocked"
    color: "ff9800"
    description: "Blocked by external factors"
  - name: "status: needs review"
    color: "7057ff"
    description: "Needs review"
  - name: "status: needs testing"
    color: "ffc107"
    description: "Needs testing"

  # Component labels
  - name: "component: rust"
    color: "ff6b6b"
    description: "Rust backend code"
  - name: "component: python"
    color: "3776ab"
    description: "Python bindings"
  - name: "component: odbc"
    color: "4caf50"
    description: "ODBC integration"
  - name: "component: arrow"
    color: "ff9800"
    description: "Arrow data processing"
  - name: "component: ci"
    color: "7057ff"
    description: "CI/CD pipeline"
  - name: "component: docs"
    color: "0075ca"
    description: "Documentation"

  # Good for contributors
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "hacktoberfest"
    color: "ff6b6b"
    description: "Hacktoberfest issues"

  # Special labels
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  - name: "invalid"
    color: "e4e669"
    description: "This doesn't seem right"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: "stale"
    color: "cfd3d7"
    description: "This issue has been automatically marked as stale"
